/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CandidaturasRouteImport } from './routes/candidaturas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropostasIndexRouteImport } from './routes/propostas.index'
import { Route as PropostasIdRouteImport } from './routes/propostas.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidaturasRoute = CandidaturasRouteImport.update({
  id: '/candidaturas',
  path: '/candidaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIndexRoute = PropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIdRoute = PropostasIdRouteImport.update({
  id: '/propostas/$id',
  path: '/propostas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidaturas': typeof CandidaturasRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/': typeof PropostasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidaturas': typeof CandidaturasRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas': typeof PropostasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidaturas': typeof CandidaturasRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/': typeof PropostasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidaturas'
    | '/dashboard'
    | '/login'
    | '/propostas/$id'
    | '/propostas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidaturas'
    | '/dashboard'
    | '/login'
    | '/propostas/$id'
    | '/propostas'
  id:
    | '__root__'
    | '/'
    | '/candidaturas'
    | '/dashboard'
    | '/login'
    | '/propostas/$id'
    | '/propostas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidaturasRoute: typeof CandidaturasRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PropostasIdRoute: typeof PropostasIdRoute
  PropostasIndexRoute: typeof PropostasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidaturas': {
      id: '/candidaturas'
      path: '/candidaturas'
      fullPath: '/candidaturas'
      preLoaderRoute: typeof CandidaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/': {
      id: '/propostas/'
      path: '/propostas'
      fullPath: '/propostas/'
      preLoaderRoute: typeof PropostasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/$id': {
      id: '/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof PropostasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidaturasRoute: CandidaturasRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PropostasIdRoute: PropostasIdRoute,
  PropostasIndexRoute: PropostasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
